apiVersion: apps/v1
kind: Deployment
metadata:
  name: primuslearning
  labels:
    app: primuslearning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: primuslearning
  template:
    metadata:
      labels:
        app: primuslearning
    spec:
      containers:
        - name: primuslearning
          image: 920373030035.dkr.ecr.ap-south-1.amazonaws.com/gitops-webapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080