name: Build and Deploy to EKS

on:
  push:
    branches:
      - feature  # or your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{vars.AWS_REGION}}
      CLUSTER_NAME: githubactions-eks
      ECR_REPO: ${{vars.ECR_REPO}}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build and Push Docker Image
      uses: appleboy/docker-ecr-action@master
      with:
        access_key: ${{ secrets.AWS_ACCESS_KEY }}
        secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: ${{ env.AWS_REGION }}
        repo: ${{ env.ECR_REPO }}
        tags: latest,${{github.run_number}}
        daemon_off: false
        dockerfile: ./DockerFile
        context: ./


   