name: Build and Deploy to EKS

on:
  push:
    branches:
      - feature  # or your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: E${{vars.AWS_REGION}}
      CLUSTER_NAME: githubactions-eks
      ECR_REPO: ${{vars.ECR_REPO}}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, Tag, and Push Docker Image to ECR
      run: |
        docker build -t $ECR_REPO:latest .
        docker push $ECR_REPO:latest

    - name: Update Kubeconfig for EKS Cluster
      run: |
        aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_REGION

    - name: Deploy to EKS
      run: |
        kubectl apply -f deployment.yml
        kubectl apply -f service.yml
