name: app deploy to EKS
on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]



env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build-infra:
    name: terraform-ci-cd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ./Terraform-vpc

      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: ./Terraform-VPC
      - name: Terraform Plan
        id: plan
        run: terraform plan
        working-directory: ./Terraform-VPC
      - name: Terraform Apply
        id: apply
        run: terraform destroy --auto-approve
        working-directory: ./Terraform-VPC

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Install kubectl
#       uses: azure/setup-kubectl@v2.0
#       with:
#         version: 'v1.24.0' # default is latest stable
#       id: install

#     - name: Configure AWS Credentials
#       uses: aws-actions/configure-aws-credentials@v1
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: ${{secrets.AWS_REGION}}

#     - name: Login to Amazon ECR
#       id: login-ecr
#       uses: aws-actions/amazon-ecr-login@v1

  
#     - name: Ensure ECR Repository Exists
#       run: |
#           aws ecr describe-repositories --repository-names primuslearning || \
#           aws ecr create-repository --repository-name primuslearning

#     - name: Build, tag, and push docker image to Amazon ECR
#       env:
#         REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#         REPOSITORY: primuslearning
#         IMAGE_TAG: 1.1
#       run: |
#         docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
#         docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

    

#     - name: Update kube config
#       run: aws eks update-kubeconfig --name primuslearning
    
#     - name: Deploy to EKS
#       run: |
#         kubectl apply -f deployment.yaml
#         kubectl apply -f service.yaml